version: '3.1'

services:

  python:
    container_name: python_web
    build: .
    environment:
    - PYTHONUNBUFFERED=1
    ports:
      - "8080:5000"

  db:
    container_name: database
    image: postgres
    env_file:
      - .env
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d